### ISSUE TITLE
Official npm package

### ISSUE THREAD

**Issue by sidd** [billyvg/node-client#5]
I noticed the [official npm package](https://npm.im/neovim/) points to this fork instead of [neovim/node-client](https://github.com/neovim/node-client), is this intended?

**Comment by billyvg** [comment]
Not intended, will update, thanks!

**Comment by billyvg** [comment]
Updated https://github.com/neovim/node-client/commit/97baa6e41113388ed05815de9292a0e7d603c6da (still need to publish package)
